service: jokes-rest-api-oreilly

frameworkVersion: ">=1.8.0 <2.0.0"

custom:
  config: ${file(./config/${opt:stage, self:provider.stage}.yml):config}

provider:
  name: aws
  stage: dev
  region: us-east-2
  runtime: nodejs6.10
  environment:
    JOKES_TABLE: ${self:custom.config.jokesTable}
    SERVERLESS_REGION: ${opt:region, self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.environment.SERVERLESS_REGION}:*:table/${self:provider.environment.JOKES_TABLE}

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: jokes
          method: post
          cors: true
  list:
    handler: handler.list
    events:
      - http:
          path: jokes
          method: get
          cors: true
  get:
    handler: handler.get
    events:
      - http:
          path: jokes/{id}
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: jokes/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: jokes/{id}
          method: delete
          cors: true

resources:
  Resources:
    JokesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.config.jokesTable}
